
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat May 11 14:35:15 CEST 2024
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class LexiconClass {
  /* terminals */
  public static final int PARENTESIS_CLOSE = 12;
  public static final int SQ_BRACKET_OPEN = 15;
  public static final int MULT_OP = 7;
  public static final int CASE = 45;
  public static final int CLASS_T = 32;
  public static final int INTEGER = 3;
  public static final int PRIVATE = 56;
  public static final int CONTINUE = 50;
  public static final int FUNC_T = 35;
  public static final int BRACKET_CLOSE = 14;
  public static final int PARENTESIS_OPEN = 11;
  public static final int FOR = 49;
  public static final int EQUAL_OP = 19;
  public static final int DEFINE = 40;
  public static final int SEMICOLON = 31;
  public static final int GREATER_OR_EQ_OP = 21;
  public static final int COMMA = 29;
  public static final int MOD_OP = 9;
  public static final int OR_OP = 25;
  public static final int TYPEDEF = 39;
  public static final int INT_T = 4;
  public static final int MAIN = 57;
  public static final int IF = 42;
  public static final int REFERENCE_OP = 37;
  public static final int THIS = 54;
  public static final int SUBS_OP = 6;
  public static final int ID = 2;
  public static final int NEW_OP = 38;
  public static final int AND_OP = 24;
  public static final int OUTPUT_FUNC = 52;
  public static final int EOF = 0;
  public static final int RETURN = 53;
  public static final int NOT_OP = 26;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int LESS_OP = 17;
  public static final int SUM_OP = 5;
  public static final int LESS_OR_EQ_OP = 20;
  public static final int BREAK = 46;
  public static final int BOOLEAN_T = 23;
  public static final int BRACKET_OPEN = 13;
  public static final int FIELD_ACCESS = 34;
  public static final int SWITCH = 44;
  public static final int STRUCT_T = 33;
  public static final int POINTER_OP = 36;
  public static final int NOT_EQUAL_OP = 22;
  public static final int COLON = 30;
  public static final int ELSE = 43;
  public static final int GREATER_OP = 18;
  public static final int WHILE = 48;
  public static final int POW_OP = 10;
  public static final int DIV_OP = 8;
  public static final int DEFAULT = 47;
  public static final int PUBLIC = 55;
  public static final int SQ_BRACKET_CLOSE = 16;
  public static final int ASSIGNATION_OP = 41;
  public static final int FALSE = 28;
  public static final int INPUT_FUNC = 51;
}

