
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Apr 03 19:13:52 CEST 2024
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class LexiconClass {
  /* terminals */
  public static final int PARENTESIS_CLOSE = 11;
  public static final int SQ_BRACKET_OPEN = 14;
  public static final int MULT_OP = 7;
  public static final int CASE = 44;
  public static final int CLASS_T = 31;
  public static final int INTEGER = 2;
  public static final int PRIVATE = 54;
  public static final int CONTINUE = 48;
  public static final int FUNC_T = 34;
  public static final int BRACKET_CLOSE = 13;
  public static final int PARENTESIS_OPEN = 10;
  public static final int EQUAL_OP = 18;
  public static final int DEFINE = 39;
  public static final int SEMICOLON = 30;
  public static final int GREATER_OR_EQ_OP = 20;
  public static final int COMMA = 28;
  public static final int OR_OP = 24;
  public static final int TYPEDEF = 38;
  public static final int INT_T = 4;
  public static final int MAIN = 55;
  public static final int IF = 41;
  public static final int REFERENCE_OP = 36;
  public static final int THIS = 52;
  public static final int SUBS_OP = 6;
  public static final int ID = 3;
  public static final int NEW_OP = 37;
  public static final int AND_OP = 23;
  public static final int OUTPUT_FUNC = 50;
  public static final int EOF = 0;
  public static final int RETURN = 51;
  public static final int NOT_OP = 25;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int LESS_OP = 16;
  public static final int SUM_OP = 5;
  public static final int LESS_OR_EQ_OP = 19;
  public static final int BREAK = 45;
  public static final int BOOLEAN_T = 22;
  public static final int BRACKET_OPEN = 12;
  public static final int FIELD_ACCESS = 33;
  public static final int SWITCH = 43;
  public static final int STRUCT_T = 32;
  public static final int POINTER_OP = 35;
  public static final int NOT_EQUAL_OP = 21;
  public static final int COLON = 29;
  public static final int ELSE = 42;
  public static final int GREATER_OP = 17;
  public static final int WHILE = 47;
  public static final int POW_OP = 9;
  public static final int DIV_OP = 8;
  public static final int DEFAULT = 46;
  public static final int PUBLIC = 53;
  public static final int SQ_BRACKET_CLOSE = 15;
  public static final int ASSIGNATION_OP = 40;
  public static final int FALSE = 27;
  public static final int INPUT_FUNC = 49;
}

